on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]
  

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
